### ISSUE TITLE
Cannot use torrent_core in new project

### ISSUE THREAD

**Issue by edescourtis** [jlouis/etorrent_core#16]
I keep getting issues with cascadae and etorrent_core recursively entering each others directories. Is there a stable version that is know to be embeddable?

**Comment by jlouis** [comment]
Not at the moment, unfortunately. See etorrent/#142 for the underlying problem.

**Comment by edescourtis** [comment]
I am interested in fixing the problem since I need it in a project I am working on.

**Comment by jlouis** [comment]
cascadae has been split from the core now, but the state is somewhat that it is kind of unusable, still.
