### ISSUE TITLE
Change URL for meck project

### ISSUE THREAD

**Issue by hummermania** [jlouis/etorrent_core#4]
Check the new URL for meck project. Last user - klaar, and new is "eproxus". But when I try change this in rebar.config I see some errors:

-Pulling meck from {git,"git://github.com/eproxus/meck.git", "file-bif-passthrough"}
-Initialized empty Git repository in /home/...../etorrent_core/deps/meck/.git/
-error: pathspec 'file-bif-passthrough' did not match any file(s) known to git.
-ERROR: git checkout -q file-bif-passthrough failed with error: 1 and output:
-error: pathspec 'file-bif-passthrough' did not match any file(s) known to git.

ERROR: 'get-deps' failed while processing /home/.../etorrent_core: rebar_abort

**Comment by jlouis** [comment]
Why didn't I get on this earlier? Anyway, you are right this is a bug and I should be looking into it. I'm slowly gearing up for a run over the code and anti-bit-rotting it. There is some need for that.

**Comment by hummermania** [comment]
You didn't get this earlier because have a downloaded with rebar code of some project in /deps. If you try clear this folder and get the dependecies again, you can see all the third party project wich change URL.

**Comment by jlouis** [comment]
I have moved somewhat towards a more working version. I've pushed fixes upstream into the libraries - and when that applies certain things should clear out.
